### ISSUE TITLE
SK0NN is parsed but does not show on aprs.fi

### ISSUE THREAD

**Issue by sm0tsc** [BrandMeister/bm-rpt2aprs#3] opened 2017-09-15 11:13 UTC
getting info for repeater id 240012...
  sending location to aprs for SK0NN Stockholm
    aprs text: SK0NN 434.5375/432.5375 CC1
    aprs data: SK0NN Stockholm>APRS,TCPIP*:@151111z5910.16N/01808.39ErPHG7490SK0                                                                                                                                                             NN 434.5375/432.5375 CC1

**Comment by nonoo** [comment] 2017-09-15 11:14
Log shows that the packet has been sent, so the issue is not with bm-rpt2aprs.

**Comment by sm0tsc** [comment] 2017-09-15 11:24
So why is it not showing? Its the same with SK0RYG

getting info for repeater id 240097...
  sending location to aprs for SK0RYG Väsby
    aprs text: RD985 434.7625/432.7625 CC1
    aprs data: SK0RYG Väsby>APRS,TCPIP*:@151112z5931.43N/01755.34ErPHG5190RD985 434.7625/432.7625 CC1

Also SK6QA it seems there is some issuses when there are other APRS objects with the same call but other SSID

**Comment by pjao** [comment] 2017-09-15 11:36
If you look (https://aprs.fi/?c=raw&call=SK0RYG&limit=50&view=normal)
the message is "Invalid uncompressed location".

Don't know what it the error and if it is from "bm-rpt2aprs" codification or what else...

![imagem](https://user-images.githubusercontent.com/6640329/30480524-0e05000c-9a12-11e7-8f88-15514a500946.png)

**Comment by sm0tsc** [comment] 2017-09-15 11:37
SK0RMQ-14 is the script

**Comment by sm0tsc** [comment] 2017-09-15 11:55
Please note there is multiple SK0RYG repeaters.. And in the SK0NN case there is one DMR repeater but several other APRS objects with other ssid

**Comment by pjao** [comment] 2017-09-15 12:01
I thinks that the error came from the coordinates

SK0RYG "42.00N/01754.100E"
and
SK0RYG-1 "31.43NI01755.34E"

that ".100E"

I've also a repeater with that problem in the W coordinates,

**Comment by pjao** [comment] 2017-09-15 13:52
Made a possible fix to this issue (https://github.com/BrandMeister/bm-rpt2aprs/pull/4)

**Comment by pjao** [comment] 2017-09-15 15:33
@sm0tsc please get the last version with "git pull" and try to see if your problem is solved.

**Comment by sm0tsc** [comment] 2017-09-16 13:38
Seem to be partly solved.. SK0RYG now shows but not SK0NN

**Comment by pjao** [comment] 2017-09-16 16:55
From SK0NN can't see any information that is send to aprs.fi

https://aprs.fi/?c=raw&call=SK0NN&limit=50&view=normal

Can you post or send the lines from the output run of bm-rpt2aprs?

Paulo - CT2JAY

**Comment by sm0tsc** [comment] 2017-09-16 17:59
connecting to aprs...
getting info for repeater id 240003...
  sending location to aprs for SM0WIU-R
    aprs text: M27QNR9JA7AN 434.8750/432.8750 CC1
    aprs data: SM0WIU-R>APRS,TCPIP*:@161758z5915.04N/01752.73ErPHG7490M27QNR9JA7AN 434.8750/432.8750 CC1
getting info for repeater id 240611...
  invalid coordinates, ignoring
getting info for repeater id 240401...
  invalid coordinates, ignoring
getting info for repeater id 240612...
  invalid coordinates, ignoring
getting info for repeater id 240701...
  sending location to aprs for SK7RJL
    aprs text: M27QPR9JA7AN 434.5875/432.5875 CC7
    aprs data: SK7RJL>APRS,TCPIP*:@161758z5543.63N/01313.73ErPHG6370M27QPR9JA7AN 434.5875/432.5875 CC7
getting info for repeater id 240610...
  invalid coordinates, ignoring
getting info for repeater id 240012...
  sending location to aprs for SK0NN Stockholm
    aprs text: SK0NN 434.5375/432.5375 CC1
    aprs data: SK0NN Stockholm>APRS,TCPIP*:@161758z5910.16N/01808.39ErPHG7490SK0NN 434.5375/432.5375 CC1
getting info for repeater id 2406018...
  invalid coordinates, ignoring
getting info for repeater id 2407221...
  sending location to aprs for SA7MIC
    aprs text: openSPOT 433.5500/433.5500 CC1
    aprs data: SA7MIC>APRS,TCPIP*:@161758z5603.72N/01312.48EQopenSPOT 433.5500/433.5500 CC1
getting info for repeater id 2404041...
  invalid coordinates, ignoring
getting info for repeater id 2406016...
  sending location to aprs for SM6ZDO
    aprs text: Windows:BlueDV 433.6125/433.6125 CC1
    aprs data: SM6ZDO>APRS,TCPIP*:@161758z5200.00N/00500.00EQWindows:BlueDV 433.6125/433.6125 CC1
getting info for repeater id 2407229...
  sending location to aprs for SM7LWL
    aprs text: Windows:BlueDV 433.5500/433.5500 CC1
    aprs data: SM7LWL>APRS,TCPIP*:@161758z1300.00N/05600.00EQWindows:BlueDV 433.5500/433.5500 CC1
getting info for repeater id 2406037...
  sending location to aprs for SD6GB
    aprs text: openSPOT 434.4625/434.4625 CC1
    aprs data: SD6GB>APRS,TCPIP*:@161758z5740.02N/01202.34EQPHG1530openSPOT 434.4625/434.4625 CC1
getting info for repeater id 2406017...
  invalid coordinates, ignoring
getting info for repeater id 2404010...
  sending location to aprs for SA4AVE
    aprs text: openSPOT 433.4250/433.4250 CC1
    aprs data: SA4AVE>APRS,TCPIP*:@161758z5937.08N/01309.30EQopenSPOT 433.4250/433.4250 CC1
getting info for repeater id 24061052...
  invalid coordinates, ignoring
getting info for repeater id 2400061...
  sending location to aprs for SA0CIA
    aprs text: Windows:BlueDV 433.4500/433.4500 CC1
    aprs data: SA0CIA>APRS,TCPIP*:@161758z5203.42N/00504.43EQWindows:BlueDV 433.4500/433.4500 CC1
getting info for repeater id 2404066...
  invalid coordinates, ignoring
getting info for repeater id 2406160...
  invalid coordinates, ignoring
getting info for repeater id 2403082...
  sending location to aprs for SA3ARQ
    aprs text: openSPOT 434.5500/434.5500 CC0
    aprs data: SA3ARQ>APRS,TCPIP*:@161758z6038.70N/01707.50EQopenSPOT 434.5500/434.5500 CC0
getting info for repeater id 2407189...
  sending location to aprs for SM7AWE
    aprs text: openSPOT 434.3000/434.3000 CC1
    aprs data: SM7AWE>APRS,TCPIP*:@161758z5533.75N/01422.50EQPHG0100openSPOT 434.3000/434.3000 CC1
getting info for repeater id 2403013...
  sending location to aprs for SM3DYE
    aprs text: Windows:BlueDV 433.6250/433.6250 CC1
    aprs data: SM3DYE>APRS,TCPIP*:@161758z5203.42N/00504.43EQWindows:BlueDV 433.6250/433.6250 CC1
getting info for repeater id 2406032...
  invalid coordinates, ignoring
getting info for repeater id 2404006...
  invalid coordinates, ignoring
getting info for repeater id 2405097...
  sending location to aprs for SM5YBE
    aprs text: openSPOT 433.6325/433.6325 CC1
    aprs data: SM5YBE>APRS,TCPIP*:@161758z6036.24N/01727.48EQopenSPOT 433.6325/433.6325 CC1
getting info for repeater id 2406006...
  sending location to aprs for SA6BWX
    aprs text: openSPOT 433.4000/433.4000 CC6
    aprs data: SA6BWX>APRS,TCPIP*:@161758z5743.74N/01257.48EQopenSPOT 433.4000/433.4000 CC6
getting info for repeater id 2407008...
  sending location to aprs for SA7AGP
    aprs text: openSPOT 434.4250/434.4250 CC1
    aprs data: SA7AGP>APRS,TCPIP*:@161758z5652.98N/01449.26EQPHG0100openSPOT 434.4250/434.4250 CC1
getting info for repeater id 2406009...
  sending location to aprs for SA6BXE
    aprs text: openSPOT 434.0000/434.0000 CC1
    aprs data: SA6BXE>APRS,TCPIP*:@161758z5743.74N/01257.48EQopenSPOT 434.0000/434.0000 CC1
getting info for repeater id 2403083...
  sending location to aprs for SM3WEO
    aprs text: openSPOT 437.9875/437.9875 CC3
    aprs data: SM3WEO>APRS,TCPIP*:@161758z6038.70N/01707.50EQPHG0300openSPOT 437.9875/437.9875 CC3
getting info for repeater id 2405091...
  invalid coordinates, ignoring
getting info for repeater id 2400192...
  sending location to aprs for SM0IKR
    aprs text: openSPOT 434.4625/434.4625 CC1
    aprs data: SM0IKR>APRS,TCPIP*:@161758z5914.64N/01805.40EQPHG0230openSPOT 434.4625/434.4625 CC1
getting info for repeater id 2407046...
  invalid coordinates, ignoring
getting info for repeater id 2400202...
  sending location to aprs for SM0VXI
    aprs text: openSPOT 433.5625/433.5625 CC1
    aprs data: SM0VXI>APRS,TCPIP*:@161758z5921.18N/01805.34EQPHG0200openSPOT 433.5625/433.5625 CC1
getting info for repeater id 2406058...
  sending location to aprs for SM6VTT
    aprs text: openSPOT 433.4000/433.4000 CC1
    aprs data: SM6VTT>APRS,TCPIP*:@161758z5816.20N/01217.52EQPHG0300openSPOT 433.4000/433.4000 CC1
getting info for repeater id 2407183...
  sending location to aprs for SG7WDL
    aprs text: openSPOT 434.2125/434.2125 CC7
    aprs data: SG7WDL>APRS,TCPIP*:@161758z5642.18N/01420.10EQPHG0100openSPOT 434.2125/434.2125 CC7
getting info for repeater id 2406035...
  sending location to aprs for SM6VTT
    aprs text: openSPOT 434.4000/434.4000 CC1
    aprs data: SM6VTT>APRS,TCPIP*:@161758z5816.20N/01217.52EQPHG0300openSPOT 434.4000/434.4000 CC1
getting info for repeater id 2407210...
  sending location to aprs for SM7FGG
    aprs text: openSPOT 433.5500/433.5500 CC1
    aprs data: SM7FGG>APRS,TCPIP*:@161758z5611.22N/01547.52EQPHG0200openSPOT 433.5500/433.5500 CC1
getting info for repeater id 2405008...
  sending location to aprs for SM5TAH
    aprs text: openSPOT 434.9250/434.9250 CC5
    aprs data: SM5TAH>APRS,TCPIP*:@161758z5904.98N/01634.14EQPHG0100openSPOT 434.9250/434.9250 CC5
getting info for repeater id 2406128...
  sending location to aprs for SA6JUR
    aprs text: openSPOT 434.6750/434.6750 CC1
    aprs data: SA6JUR>APRS,TCPIP*:@161758z5753.70N/01202.52EQopenSPOT 434.6750/434.6750 CC1
getting info for repeater id 240037...
  sending location to aprs for SK0PT
    aprs text: openSPOT 434.5500/434.5500 CC1
    aprs data: SK0PT>APRS,TCPIP*:@161758z5928.74N/01742.48EQPHG0400openSPOT 434.5500/434.5500 CC1
getting info for repeater id 2403002...
  no callsign, ignoring
getting info for repeater id 2407021...
  invalid coordinates, ignoring
getting info for repeater id 2407124...
  invalid coordinates, ignoring
getting info for repeater id 2407112...
  invalid coordinates, ignoring
getting info for repeater id 0...
  no callsign, ignoring
getting info for repeater id 0...
  no callsign, ignoring
getting info for repeater id 0...
  no callsign, ignoring
getting info for repeater id 0...
  no callsign, ignoring
getting info for repeater id 0...
  no callsign, ignoring
getting info for repeater id 240306...
  sending location to aprs for SK3RFG
    aprs text: - Nolby - 434.9875/432.9875 CC3
    aprs data: SK3RFG>APRS,TCPIP*:@161758z6218.03N/01721.82ErPHG4260- Nolby - 434.9875/432.9875 CC3
getting info for repeater id 240706...
  invalid coordinates, ignoring
getting info for repeater id 2021005...
  sending location to aprs for SV1DAR
    aprs text: MMDVM DVMega 436.0250/436.0250 CC1
    aprs data: SV1DAR>APRS,TCPIP*:@161758z3734.61N/02327.04EQMMDVM DVMega 436.0250/436.0250 CC1
getting info for repeater id 2403011...
  invalid coordinates, ignoring
getting info for repeater id 2406020...
  sending location to aprs for SM6MLY
    aprs text: MMDVM DVMega 433.4500/433.4500 CC1
    aprs data: SM6MLY>APRS,TCPIP*:@161758z5740.03N/01202.36EQMMDVM DVMega 433.4500/433.4500 CC1
getting info for repeater id 2403087...
  sending location to aprs for SG3VRO
    aprs text: Mobile Hotspot 437.6125/437.6125 CC1
    aprs data: SG3VRO>APRS,TCPIP*:@161758z0100.00N/00100.00EQPHG1060Mobile Hotspot 437.6125/437.6125 CC1
getting info for repeater id 2405001...
  sending location to aprs for SM5OEM
    aprs text: MMDVM DVMega 445.9875/445.9875 CC1
    aprs data: SM5OEM>APRS,TCPIP*:@161758z3325.46N/11134.51WQMMDVM DVMega 445.9875/445.9875 CC1
getting info for repeater id 2404080...
  sending location to aprs for SG4KUH
    aprs text: MMDVM DVMega 433.4750/433.4750 CC1
    aprs data: SG4KUH>APRS,TCPIP*:@161758z6035.17N/01537.40EQMMDVM DVMega 433.4750/433.4750 CC1
getting info for repeater id 2400183...
  sending location to aprs for SE0O
    aprs text: Sodermalm/Stockholm 433.5000/433.5000 CC1
    aprs data: SE0O>APRS,TCPIP*:@161758z5918.68N/01805.41EQPHG4330Sodermalm/Stockholm 433.5000/433.5000 CC1
getting info for repeater id 2405096...
  sending location to aprs for SA5MAC
    aprs text: MMDVM DVMega 432.5500/432.5500 CC1
    aprs data: SA5MAC>APRS,TCPIP*:@161758z5834.66N/01608.36EQMMDVM DVMega 432.5500/432.5500 CC1
getting info for repeater id 240707...
  sending location to aprs for SG7RFH
    aprs text: MMDVM 434.9000/432.9000 CC7
    aprs data: SG7RFH>APRS,TCPIP*:@161758z5739.07N/01442.84ErPHG0280MMDVM 434.9000/432.9000 CC7
getting info for repeater id 240060...
  sending location to aprs for SK0MK
    aprs text: MMDVM 145.7000/145.1000 CC1
    aprs data: SK0MK>APRS,TCPIP*:@161758z5906.62N/01733.83ErPHG9390MMDVM 145.7000/145.1000 CC1
getting info for repeater id 240740...
  sending location to aprs for SK7RGI
    aprs text: MMDVM 434.9750/432.9750 CC7
    aprs data: SK7RGI>APRS,TCPIP*:@161758z5746.80N/01406.08ErPHG9180MMDVM 434.9750/432.9750 CC7
getting info for repeater id 450704...
  sending location to aprs for DS0RR
    aprs text: MMDVM 439.0100/433.0100 CC1
    aprs data: DS0RR>APRS,TCPIP*:@161758z3732.70N/12656.19ErMMDVM 439.0100/433.0100 CC1
getting info for repeater id 450705...
  sending location to aprs for DS0RS
    aprs text: MMDVM DMO 430.8000/430.8000 CC1
    aprs data: DS0RS>APRS,TCPIP*:@161758z3732.70N/12656.19EQMMDVM DMO 430.8000/430.8000 CC1
getting info for repeater id 2407004...
  sending location to aprs for SG7ADV
    aprs text: MMDVM DVMega 433.5500/433.5500 CC1
    aprs data: SG7ADV>APRS,TCPIP*:@161758z5611.67N/01320.75EQMMDVM DVMega 433.5500/433.5500 CC1
getting info for repeater id 2403091...
  sending location to aprs for SM3VOX
    aprs text: MMDVM DVMega 437.9625/437.9625 CC1
    aprs data: SM3VOX>APRS,TCPIP*:@161758z6040.06N/01704.67EQMMDVM DVMega 437.9625/437.9625 CC1
getting info for repeater id 2400186...
  sending location to aprs for SE0S
    aprs text: MMDVM DMO 433.5500/433.5500 CC1
    aprs data: SE0S>APRS,TCPIP*:@161758z5917.90N/01805.40EQPHG4340MMDVM DMO 433.5500/433.5500 CC1
getting info for repeater id 2403112...
  sending location to aprs for SG0BON
    aprs text: MMDVM DVMega 436.6125/436.6125 CC1
    aprs data: SG0BON>APRS,TCPIP*:@161758z6040.26N/01705.64EQMMDVM DVMega 436.6125/436.6125 CC1
getting info for repeater id 240240...
  sending location to aprs for SG2UQK
    aprs text: MMDVM 434.5375/432.5375 CC2
    aprs data: SG2UQK>APRS,TCPIP*:@161758z6616.68N/01639.42ErPHG4050MMDVM 434.5375/432.5375 CC2
getting info for repeater id 2403097...
  sending location to aprs for SG3BDF
    aprs text: MMDVM DVMega 433.4250/433.4250 CC1
    aprs data: SG3BDF>APRS,TCPIP*:@161758z6118.46N/01623.32EQMMDVM DVMega 433.4250/433.4250 CC1
getting info for repeater id 2403098...
  sending location to aprs for SG3VRO
    aprs text: MMDVM DVMega 433.6125/433.6125 CC1
    aprs data: SG3VRO>APRS,TCPIP*:@161758z6037.12N/01657.84EQMMDVM DVMega 433.6125/433.6125 CC1
getting info for repeater id 262544201...
  sending location to aprs for DK1OZ
    aprs text: MMDVM DMO 436.1000/436.1000 CC1
    aprs data: DK1OZ>APRS,TCPIP*:@161758z5022.38N/00709.45EQPHG4750MMDVM DMO 436.1000/436.1000 CC1
getting info for repeater id 2404019...
  sending location to aprs for SG4AXQ
    aprs text: MMDVM DMO 432.5000/432.5000 CC1
    aprs data: SG4AXQ>APRS,TCPIP*:@161758z5950.75N/01308.02EQMMDVM DMO 432.5000/432.5000 CC1
getting info for repeater id 2407219...
  sending location to aprs for SA7SVR
    aprs text: SA7SVR  Mobile Host Spot 430.5000/430.5000 CC1
    aprs data: SA7SVR>APRS,TCPIP*:@161758z5746.79N/01409.68EQPHG0020SA7SVR  Mobile Host Spot 430.5000/430.5000 CC1
getting info for repeater id 2403063...
  sending location to aprs for SG3EFS
    aprs text: Pi-Star HotSpot 433.4875/433.4875 CC1
    aprs data: SG3EFS>APRS,TCPIP*:@161758z6217.25N/01726.88EQPHG1010Pi-Star HotSpot 433.4875/433.4875 CC1
getting info for repeater id 2403087...
  sending location to aprs for SG3VRO
    aprs text: Mobile Hotspot 437.6125/437.6125 CC1
    aprs data: SG3VRO>APRS,TCPIP*:@161758z0100.00N/00100.00EQPHG1060Mobile Hotspot 437.6125/437.6125 CC1
getting info for repeater id 2400247...
  sending location to aprs for SG0WQT
    aprs text: MMDVM DVMega 434.4500/434.4500 CC1
    aprs data: SG0WQT>APRS,TCPIP*:@161758z5906.97N/01847.05EQMMDVM DVMega 434.4500/434.4500 CC1
getting info for repeater id 2404054...
  sending location to aprs for SM4WDQ
    aprs text: MMDVM DVMega 434.2000/434.2000 CC1
    aprs data: SM4WDQ>APRS,TCPIP*:@161758z6002.69N/01339.95EQPHG0500MMDVM DVMega 434.2000/434.2000 CC1
getting info for repeater id 202101503...
  sending location to aprs for SY1BRU
    aprs text: MMDVM DMO 435.7000/435.7000 CC1
    aprs data: SY1BRU>APRS,TCPIP*:@161758z3758.75N/02342.88EQPHG0400MMDVM DMO 435.7000/435.7000 CC1
getting info for repeater id 202101501...
  sending location to aprs for SY1BRU
    aprs text: MMDVM DVMega 438.0000/438.0000 CC1
    aprs data: SY1BRU>APRS,TCPIP*:@161758z3758.75N/02342.88EQMMDVM DVMega 438.0000/438.0000 CC1
getting info for repeater id 2407161...
  sending location to aprs for SG7CDJ
    aprs text: MMDVM 434.5000/432.5000 CC7
    aprs data: SG7CDJ>APRS,TCPIP*:@161758z5618.34N/01528.16ErPHG2000MMDVM 434.5000/432.5000 CC7
getting info for repeater id 2407006...
  invalid coordinates, ignoring
getting info for repeater id 240201...
  sending location to aprs for SK2RGJ
    aprs text: MMDVM 434.5125/432.5125 CC2
    aprs data: SK2RGJ>APRS,TCPIP*:@161758z6748.00N/02012.00ErPHG0700MMDVM 434.5125/432.5125 CC2
getting info for repeater id 2403117...
  sending location to aprs for SM3YFX
    aprs text: MMDVM 434.5250/432.5250 CC1
    aprs data: SM3YFX>APRS,TCPIP*:@161758z6340.22N/01436.46ErPHG5280MMDVM 434.5250/432.5250 CC1
getting info for repeater id 2400180...
  sending location to aprs for SH8IP
    aprs text: MMDVM DVMega 433.4500/433.4500 CC1
    aprs data: SH8IP>APRS,TCPIP*:@161758z5213.80N/00521.68WQMMDVM DVMega 433.4500/433.4500 CC1
getting info for repeater id 2407203...
  sending location to aprs for SK7RRV
    aprs text: MMDVM DVMega 432.5875/432.5875 CC7
    aprs data: SK7RRV>APRS,TCPIP*:@161758z1419.60N/05623.72EQMMDVM DVMega 432.5875/432.5875 CC7
getting info for repeater id 240640...
  sending location to aprs for SK6RJW
    aprs text: MMDVM 434.7250/432.7250 CC6
    aprs data: SK6RJW>APRS,TCPIP*:@161758z5723.37N/01159.98ErPHG9280MMDVM 434.7250/432.7250 CC6
getting info for repeater id 2407105...
  sending location to aprs for SG7IKJ
    aprs text: MMDVM DVMega 434.5875/434.5875 CC7
    aprs data: SG7IKJ>APRS,TCPIP*:@161758z1418.80N/05623.63EQMMDVM DVMega 434.5875/434.5875 CC7
getting info for repeater id 2400093...
  invalid coordinates, ignoring
getting info for repeater id 24061421...
  sending location to aprs for SM6TQB
    aprs text: MMDVM 434.5250/432.5250 CC6
    aprs data: SM6TQB>APRS,TCPIP*:@161758z5728.81N/01322.05ErPHG0100MMDVM 434.5250/432.5250 CC6
getting info for repeater id 2407009...
  invalid coordinates, ignoring
getting info for repeater id 240080...
  sending location to aprs for SK0RYG
    aprs text: MMDVM 434.9125/432.9125 CC1
    aprs data: SK0RYG>APRS,TCPIP*:@161758z5942.00N/01755.00ErPHG5290MMDVM 434.9125/432.9125 CC1
getting info for repeater id 240301...
  sending location to aprs for SK3RFG
    aprs text: - Kliss - 434.8000/432.8000 CC1
    aprs data: SK3RFG>APRS,TCPIP*:@161758z6222.73N/01712.23ErPHG4460- Kliss - 434.8000/432.8000 CC1
getting info for repeater id 2407188...
  invalid coordinates, ignoring
getting info for repeater id 2404077...
  sending location to aprs for SG4BYH
    aprs text: MMDVM 434.8500/432.8500 CC1
    aprs data: SG4BYH>APRS,TCPIP*:@161758z5925.39N/01329.09ErPHG4150MMDVM 434.8500/432.8500 CC1
getting info for repeater id 2407169...
  invalid coordinates, ignoring
getting info for repeater id 2400150...
  invalid coordinates, ignoring
getting info for repeater id 2407202...
  invalid coordinates, ignoring
getting info for repeater id 2407170...
  sending location to aprs for SM7WEG
    aprs text: MMDVM DVMega 433.7750/433.7750 CC1
    aprs data: SM7WEG>APRS,TCPIP*:@161758z5543.68N/01313.21EQMMDVM DVMega 433.7750/433.7750 CC1
getting info for repeater id 2404076...
  sending location to aprs for SG4JPK
    aprs text: MMDVM DMO 433.2750/433.2750 CC4
    aprs data: SG4JPK>APRS,TCPIP*:@161758z5930.31N/01318.45EQPHG6090MMDVM DMO 433.2750/433.2750 CC4
getting info for repeater id 240066...
  sending location to aprs for SK0BO
    aprs text: MMDVM DMO 433.7375/433.7375 CC1
    aprs data: SK0BO>APRS,TCPIP*:@161758z5929.50N/01851.25EQPHG0300MMDVM DMO 433.7375/433.7375 CC1
getting info for repeater id 240606...
  invalid coordinates, ignoring
getting info for repeater id 2400222...
  invalid coordinates, ignoring
getting info for repeater id 240704...
  sending location to aprs for SA7BIK HÃ¤sslehlm
    aprs text: RD625 434.9125/432.9125 CC7
    aprs data: SA7BIK HÃ¤sslehlm>APRS,TCPIP*:@161758z5609.85N/01347.40ErPHG5370RD625 434.9125/432.9125 CC7
getting info for repeater id 240604...
  sending location to aprs for SK6IF-Kungshamn
    aprs text: RD985 145.5750/144.9750 CC6
    aprs data: SK6IF-Kungshamn>APRS,TCPIP*:@161758z5821.41N/01115.24ErPHG4330RD985 145.5750/144.9750 CC6
getting info for repeater id 240703...
  sending location to aprs for SK7REP
    aprs text: RD985 434.7750/432.7750 CC7
    aprs data: SK7REP>APRS,TCPIP*:@161758z5536.80N/01258.59ErPHG7580RD985 434.7750/432.7750 CC7
getting info for repeater id 240524...
  sending location to aprs for SG5DV
    aprs text: RD985 434.5875/432.5875 CC1
    aprs data: SG5DV>APRS,TCPIP*:@161758z5949.76N/01739.27ErPHG6290RD985 434.5875/432.5875 CC1
getting info for repeater id 240602...
  sending location to aprs for SK6AG
    aprs text: RD625 434.7875/432.7875 CC6
    aprs data: SK6AG>APRS,TCPIP*:@161758z5740.71N/01158.72ErPHG5460RD625 434.7875/432.7875 CC6
getting info for repeater id 240702...
  sending location to aprs for SK7REE
    aprs text: RD985 434.6500/432.6500 CC7
    aprs data: SK7REE>APRS,TCPIP*:@161758z5603.01N/01306.54ErPHG6390RD985 434.6500/432.6500 CC7
getting info for repeater id 240503...
  sending location to aprs for SK5RYG
    aprs text: RD985 434.5125/432.5125 CC5
    aprs data: SK5RYG>APRS,TCPIP*:@161758z5833.64N/01532.26ErPHG5590RD985 434.5125/432.5125 CC5
getting info for repeater id 240090...
  sending location to aprs for SK0SX Kista
    aprs text: RD985 434.9875/432.9875 CC1
    aprs data: SK0SX Kista>APRS,TCPIP*:@161758z5924.06N/01756.82ErPHG5590RD985 434.9875/432.9875 CC1
getting info for repeater id 240402...
  sending location to aprs for SK4KIL
    aprs text: RD985 145.5750/144.9750 CC4
    aprs data: SK4KIL>APRS,TCPIP*:@161758z5930.26N/01318.36ErPHG7180RD985 145.5750/144.9750 CC4
getting info for repeater id 244002...
  sending location to aprs for OH0RUB
    aprs text: RD985 434.5500/432.5500 CC1
    aprs data: OH0RUB>APRS,TCPIP*:@161758z6007.93N/01955.64ErPHG7290RD985 434.5500/432.5500 CC1
getting info for repeater id 240302...
  sending location to aprs for SK3XX
    aprs text: RD985 434.5250/432.5250 CC3
    aprs data: SK3XX>APRS,TCPIP*:@161758z6118.86N/01705.56ErPHG7270RD985 434.5250/432.5250 CC3
getting info for repeater id 240015...
  sending location to aprs for SK0MM  - VÃ„RMDÃ–
    aprs text: RD985 434.9750/432.9750 CC1
    aprs data: SK0MM  - VÃ„RMDÃ–>APRS,TCPIP*:@161758z5918.78N/01825.50ErPHG7490RD985 434.9750/432.9750 CC1
getting info for repeater id 240603...
  sending location to aprs for SK6QA Repeater
    aprs text: RD625 145.7125/145.1125 CC6
    aprs data: SK6QA Repeater>APRS,TCPIP*:@161758z5808.92N/01149.51ErPHG6340RD625 145.7125/145.1125 CC6
getting info for repeater id 240007...
  sending location to aprs for SM0WIU NynÃ¤shamn
    aprs text: RD625 434.6125/432.6125 CC1
    aprs data: SM0WIU NynÃ¤shamn>APRS,TCPIP*:@161758z5853.93N/01756.15ErPHG5350RD625 434.6125/432.6125 CC1
getting info for repeater id 240070...
  sending location to aprs for SK0RYG Sthlm
    aprs text: RD985 434.9125/432.9125 CC1
    aprs data: SK0RYG Sthlm>APRS,TCPIP*:@161758z5911.64N/01738.13ErPHG3190RD985 434.9125/432.9125 CC1
getting info for repeater id 240304...
  sending location to aprs for SK3GY Ockelbo
    aprs text: RD985 434.5750/432.5750 CC3
    aprs data: SK3GY Ockelbo>APRS,TCPIP*:@161758z6054.07N/01637.61ErPHG7650RD985 434.5750/432.5750 CC3
getting info for repeater id 240563...
  sending location to aprs for SA5BCG/R
    aprs text: RD625 434.5250/432.5250 CC1
    aprs data: SA5BCG/R>APRS,TCPIP*:@161758z5944.11N/01748.05ErPHG5190RD625 434.5250/432.5250 CC1
getting info for repeater id 240305...
  sending location to aprs for SK3GK
    aprs text: RD625 434.7375/432.7375 CC3
    aprs data: SK3GK>APRS,TCPIP*:@161758z6038.95N/01707.32ErPHG5170RD625 434.7375/432.7375 CC3
getting info for repeater id 240097...
  sending location to aprs for SK0RYG VÃ¤sby
    aprs text: RD985 434.7625/432.7625 CC1
    aprs data: SK0RYG VÃ¤sby>APRS,TCPIP*:@161758z5931.43N/01755.34ErPHG5190RD985 434.7625/432.7625 CC1
getting info for repeater id 240601...
  sending location to aprs for SL6ZAQ
    aprs text: RD985 145.6375/145.0375 CC6
    aprs data: SL6ZAQ>APRS,TCPIP*:@161758z5820.01N/01150.53ErPHG5430RD985 145.6375/145.0375 CC6
getting info for repeater id 240711...
  sending location to aprs for SK7RJL Hbg
    aprs text: RD625 434.6000/432.6000 CC7
    aprs data: SK7RJL Hbg>APRS,TCPIP*:@161758z5602.17N/01242.23ErPHG4420RD625 434.6000/432.6000 CC7
getting info for repeater id 240501...
  sending location to aprs for SL5ZYT
    aprs text: RD625 434.9500/432.9500 CC1
    aprs data: SL5ZYT>APRS,TCPIP*:@161758z5823.40N/01616.20ErPHG5590RD625 434.9500/432.9500 CC1

**Comment by pjao** [comment] 2017-09-16 18:15
I think the problem is the space between CallSign and LocationName

Example: You have "SK7RJL" and "SK7RJL Hbg". Only the first one is send to APRS network.

You must have something like underscore "SK7RJL_Hbg" and no spaces.

The reason because SK0NN didn't appear is that you have only one entry with "SK0NN Stockholm". Try remove Stockholm or add underscore "SK0NN_Stockholm".

![imagem](https://user-images.githubusercontent.com/6640329/30514665-9f91109c-9b11-11e7-9912-1c5d701875d9.png)

**Comment by sm0tsc** [comment] 2017-09-16 18:21
That will be hard as it is on a hard to access building... Is there any possibility to fix this is in code of script?

**Comment by pjao** [comment] 2017-09-16 22:58
Just make a PR with the fix.

I think this solves lots of problems you have, since lots of repeaters callsigns have spaces and don't appear on aprs.fi

Note: I've made some more tests and the underscore is also a not valid, so have to change it to "-"

**Comment by sm0tsc** [comment] 2017-09-17 08:09
Great we await eagerly the new version

//Johan

**Comment by sm0tsc** [comment] 2017-09-17 10:35
I tried your aprs.inc.php in the PR SK0NN still do not show aswell SK0SX and others

//J

**Comment by sm0tsc** [comment] 2017-09-17 11:23
Here is some extract from the log

getting info for repeater id 240012...
  sending location to aprs for SK0NN Stockholm
    aprs text: SK0NN 434.5375/432.5375 CC1
    aprs data: SK0NN-Stockholm>APRS,TCPIP*:@171120z5910.16N/01808.39ErPHG7490SK0NN 434.5375/432.5375 CC1


getting info for repeater id 240090...
  sending location to aprs for SK0SX Kista
    aprs text: RD985 434.9875/432.9875 CC1
    aprs data: SK0SX-Kista>APRS,TCPIP*:@171121z5924.06N/01756.82ErPHG5590RD985 434.9875/432.9875 CC1

//Johan SM0TSC

**Comment by pjao** [comment] 2017-09-17 13:23
Fix is rejected, because is not AX.25 complaint.

Don't know another way, just get into the building and fix it.

**Comment by pjao** [comment] 2017-09-19 09:35
@sm0tsc with last change made, close this issue if is solved and fixed.

**Closed as completed** 2017-09-20 06:51 UTC
